### PR TITLE
Add openstackclient to the auto-updater

### PR DESCRIPTION
**Pull request by graham-at-target**

### CODE REVIEW

**Comment by garbas** [comment]
@graham-at-target would you be also willing to take maintenance over? when build fails we can ping you. If yes, just add yourself to README.rst as well.

**Comment by graham-at-target** [comment]
Maybe @nlewo would like to? He's more of a user than I am :$ :)

**Comment by garbas** [comment]
I see that @nlewo opened a #23 already. I will close it and this should make it update automatically from now on.

**Comment by graham-at-target** [comment]
Cool!

**Comment by garbas** [comment]
openstackclient set is green, but we need to fix other sets

**Comment by nlewo** [comment]
I added myself as maintainer in #29. Thx for this PR!

**Pull request merged**
