### PR TITLE
ckan: init  

### PR DESCRIPTION
**Pull request by sorki**
Requires https://github.com/garbas/pypi2nix/pull/169

### CODE REVIEW

**Comment by sorki** [comment]
Didn't add this to travis.yml, would fail anyway due to setuptools version requirement.

**Comment by garbas** [comment]
Now that setuptools is updated I rebased on current master and added ckan to ``.travis.yml`` lets see if it gets green

**Comment by sorki** [comment]
Need to update this, upstream merged one important piece.

**Comment by sorki** [comment]
Seems good to go, I can deploy an instance with this now. Not sure about travis though.

**Review by garbas — APPROVED** [review]

**Pull request merged**
