### PR TITLE
new package set: home-assistant

### PR DESCRIPTION
**Pull request by garbas**
This is here to hold conversation as we progress on packaging home-assistant with `pypi2nix`.

---

This change is [Reviewable](https://reviewable.io/reviews/garbas/nixpkgs-python/2)

### CODE REVIEW

**Comment by garbas** [comment]
@peterhoeg i've added a minimal version homeassistant to nixpkgs-python and it starts up for me ok. now i guess next steps would be to add one by one extra components.

**Comment by peterhoeg** [comment]
Thanks @garbas, I have unfortunately had very little time for play-related packages, so there has been no progress on this side. I hope to give a go during the upcoming holidays.

**Comment by garbas** [comment]
@peterhoeg no worries, i'm busy also myself. now we have an initial piece done. i guess we can now add one component at the time.

**Comment by garbas** [comment]
and i actually started to really look at homeassistant to use with my laptop :P really interesting project

**Pull request merged**
